### ISSUE TITLE
Problems with dataloading (speed and `no common residues found!` error)

### ISSUE THREAD

**Issue by eswan01** [pinder-org/pinder#23]
Hi,

I wanted to raise a couple questions about the `PinderLoader` and intended use of the `PinderDataset` example. I've noticed that my training runs are spending a lot of time in the dataloading phase, so I went back to look at the loading times from each of these. I'm using the `train_dataset` and loader from the [notebook example](https://github.com/plinder-org/moving_beyond_memorisation/blob/main/notebooks/pinder.ipynb) shared in the workshop.

**Problems:**
- Oftentimes, when I load an example from any of the built in loaders, I get a `pinder.core.loader.structure:595 | ERROR : no common residues found!` error, which doesn't interrupt my code, but is maybe a cause for concern?
  - Should I be concerned about this output? If so, how might I debug this?
- The built in loaders are prohibitively slow for use in model training. I've attached a screenshot of me loading the 10 samples from the dataset in the workshop example. It takes 3-6 seconds to load this many samples, which translates to many days if iterating over the entire PINDER training dataset.
  - Is there a faster way to access the data post-splitting/filtering? I would like to use the built-in loaders as much as possible. Increasing batch size leads to some speed increase, but is still much slower than I would like.

![image](https://github.com/user-attachments/assets/009e281e-6cae-4f81-938d-54f9b0df711e)

**Environment details:**
- Installed `pinder` from github repo, latest commit on main since 2024-09-29
- Downloaded pinder dataset to local directory using the provided `pinder_download` script, and am accessing it as my `PINDER_BASE_DIR`
- Running on a capable `g6e.4xlarge` AWS EC2 instance with 16 cores and 128GB RAM

Here is the code from the notebook, defining filters and the dataset selections:
```
from pinder.core.loader.dataset import PinderDataset, structure2tensor_transform
from pinder.core.loader import filters, transforms

# We'll start by restricting the training dataset to a smaller size (10) for testing purposes.

base_filters = [
    filters.FilterByMissingHolo(),
    filters.FilterSubByContacts(min_contacts=5, radius=10.0, calpha_only=True),
    filters.FilterDetachedHolo(radius=12, max_components=2),
]
sub_filters = [
    filters.FilterSubByAtomTypes(min_atom_types=4),
    filters.FilterByHoloOverlap(min_overlap=5),
    filters.FilterByHoloSeqIdentity(min_sequence_identity=0.8),
    filters.FilterSubRmsds(rmsd_cutoff=7.5),
    filters.FilterDetachedSub(radius=12, max_components=2),
]


# We can include Structure-level transforms (and filters) which will operate on the target and/or feature complexes
target_transforms = [
    transforms.SelectAtomTypes(atom_types=["CA", "N", "C", "O"]),
]
# In addition to slicing only backbone atoms, we introduce random rotation to the ligand protein
# in the feature complex while preserving the target (ground-truth) complex orientations.
feature_transforms = [
    transforms.SelectAtomTypes(atom_types=["CA", "N", "C", "O"]),
    transforms.RandomLigandTransform(max_translation=10.0),
]

datasets = []

for split, subset_ids in [("train", training_subset), ("val", validation_subset), ("test", test_subset)]:
    print(f"Loading {split} split with {len(subset_ids)} systems...")
    dataset = PinderDataset(
        split=split,
        ids=subset_ids,
        # We can leverage holo, apo, pred, random and random_mixed monomer sampling strategies
        monomer_priority="random_mixed" if split != "test" else "holo",
        base_filters = base_filters,
        sub_filters = sub_filters,
        structure_transforms_target=target_transforms,
        structure_transforms_feature=feature_transforms)
    datasets.append(dataset)

train_dataset, val_dataset, test_dataset = datasets

assert len(train_dataset) == len(training_subset) == n_samples
assert len(test_subset) == 1
```

**Comment by danielkovtun** [comment]
Hi @eswan01 , 

## Starting with your first question

> Oftentimes, when I load an example from any of the built in loaders, I get a pinder.core.loader.structure:595 | ERROR : no common residues found! error, which doesn't interrupt my code, but is maybe a cause for concern?
> Should I be concerned about this output? If so, how might I debug this?

The error gets emitted from this function: https://github.com/pinder-org/pinder/blob/main/src/pinder-core/pinder/core/loader/structure.py#L532-L606

that function is used in one of the filters in the above setup: `filters.FilterByHoloOverlap(min_overlap=5)` 

> Should I be concerned about this output? If so, how might I debug this?
In general, no reason to be concerned, the filter is doing what it was intended to do. Perhaps we should reduce the log level there to warning, but it does indicate that for the specific apo<->holo pairing sampled in the loader, the residues are indeed insufficiently intersecting at the uniprot level. 

If we look at one such example below, for the train system ID `1qqp__C46_P03305--1qqp__C47_P03305` and the corresponding `apo_R_pdb` `4qbb__A1_P03305.pdb`, we see that while there are some shared folds, the resolved domains in the apo structure are not great matches for the holo structure: 
<img width="1546" alt="image" src="https://github.com/user-attachments/assets/73094fea-55d7-476a-aadc-56b00f3c4fba">

This example was annotated appropriately in the index with `apo_R_quality=="low"`. If you want to leave that filter in the list of filters, but wish to reduce the number of such noisy systems being sampled, you could pre-filter the index to not include systems where `apo_R_quality !="low" and apo_L_quality != "low"`. 

For example, if following the original notebook you mentioned, you could modify the `get_subset` function to look like e.g. this:
```python
def get_subset(index, split, n_samples=50):
    index_merge = pd.merge(index, metadata[["id", "resolution", "label", "method"]], on="id")
    query_list = [
        '(resolution < 2)',
        '(method == "X-RAY DIFFRACTION")',
        '(label == "BIO")',
        '(apo_R_quality != "low")',
        '(apo_L_quality != "low")',
    ]
    query = " and ".join(query_list)
    subset = index_merge.query(f'{query} and (split == "{split}")').sample(n_samples).reset_index(drop=True, inplace=False).id.to_list()
    return subset

```

You can debug this example (or rather, understand why it is raising the log error) by investigating the `mask_common_uniprot` function for the two monomers:
```python
pid = "1qqp__C46_P03305--1qqp__C47_P03305"
ps = PinderSystem(pid)
holo = ps.holo_receptor
apo = ps.apo_receptor
map_A = apo.resolved_mapping
map_B = holo.resolved_mapping
>>> map_A.sort_values("resi_uniprot")
    entry_id  entity_id asym_id pdb_strand_id  resi  resi_pdb resi_auth resn one_letter_code_can  resolved one_letter_code_uniprot  resi_uniprot uniprot_acc chain
0       4qbb          1       A             A     1        29      29.0  MET                   M         1                       M            29      P03305    A1
1       4qbb          1       A             A     2        30      30.0  GLU                   E         1                       E            30      P03305    A1
2       4qbb          1       A             A     3        31      31.0  LEU                   L         1                       L            31      P03305    A1
3       4qbb          1       A             A     4        32      32.0  THR                   T         1                       T            32      P03305    A1
4       4qbb          1       A             A     5        33      33.0  LEU                   L         1                       L            33      P03305    A1
..       ...        ...     ...           ...   ...       ...       ...  ...                 ...       ...                     ...           ...         ...   ...
154     4qbb          1       A             A   155       183     183.0  TYR                   Y         1                       Y           183      P03305    A1
155     4qbb          1       A             A   156       184     184.0  ASP                   D         1                       D           184      P03305    A1
156     4qbb          1       A             A   157       185     185.0  GLN                   Q         1                       Q           185      P03305    A1
157     4qbb          1       A             A   158       186     186.0  GLU                   E         1                       E           186      P03305    A1
158     4qbb          1       A             A   159       187     187.0  PRO                   P         1                       P           187      P03305    A1

[159 rows x 14 columns]
>>> map_B.sort_values("resi_uniprot")
    entry_id  entity_id asym_id pdb_strand_id  resi  resi_pdb resi_auth resn one_letter_code_can  resolved one_letter_code_uniprot  resi_uniprot uniprot_acc chain
0       1qqp          3       C             3     1         1         1  GLY                   G         1                       G           505      P03305   C46
1       1qqp          3       C             3     2         2         2  ILE                   I         1                       I           506      P03305   C46
2       1qqp          3       C             3     3         3         3  PHE                   F         1                       F           507      P03305   C46
3       1qqp          3       C             3     4         4         4  PRO                   P         1                       P           508      P03305   C46
4       1qqp          3       C             3     5         5         5  VAL                   V         1                       V           509      P03305   C46
..       ...        ...     ...           ...   ...       ...       ...  ...                 ...       ...                     ...           ...         ...   ...
215     1qqp          3       C             3   216       216       216  ASP                   D         1                       D           720      P03305   C46
216     1qqp          3       C             3   217       217       217  ALA                   A         1                       A           721      P03305   C46
217     1qqp          3       C             3   218       218       218  ARG                   R         1                       R           722      P03305   C46
218     1qqp          3       C             3   219       219       219  ALA                   A         1                       A           723      P03305   C46
219     1qqp          3       C             3   220       220       220  GLU                   E         1                       E           724      P03305   C46
```  

As you can see, in this example the uniprot residue span for the holo receptor is 505-724, but the apo is 29-187. 

Since the default behavior in the loader is `fallback_to_holo=True`, this wouldn't actually be "removed" unless it fails system-level filters, but would fail to select an apo monomer with the rest of the filters unchanged. 

More details on _why_  these "low" quality apo pairings exist in the first place here: 
* https://github.com/pinder-org/pinder?tab=readme-ov-file#6-%E2%84%B9%EF%B8%8F-filters--annonations
* https://github.com/pinder-org/pinder/blob/main/src/pinder-data/pinder/data/get_splits.py#L465-L632
* Also covered in the pre-print https://www.biorxiv.org/content/10.1101/2024.07.17.603980v4

I will reply to your second question in a separate comment shortly.

**Comment by danielkovtun** [comment]
## Regarding loading speed

> The built in loaders are prohibitively slow for use in model training. I've attached a screenshot of me loading the 10 samples from the dataset in the workshop example. It takes 3-6 seconds to load this many samples, which translates to many days if iterating over the entire PINDER training dataset.
> Is there a faster way to access the data post-splitting/filtering? I would like to use the built-in loaders as much as possible. Increasing batch size leads to some speed increase, but is still much slower than I would like. 
> 

In general, the filters used in the tutorial notebook are meant to serve as an illustration of some of the available filters, but are not necessarily required/recommended for all use-cases. Some of those filters, especially those that operate on the sub-component (alternate monomer) level, can add some overhead which you may or may not need to incur. 

As a general rule of thumb, I would recommend always starting with filtering applied on the index/metadata-level a priori, followed by the loader-defined filters which require loading and performing calculations on the structure objects. 

While it is certainly _valid_ to use the entirety of the training dataset, I would not recommend doing so as there is a high degree of redundancy and some noise within certain systems. If helpful, this is the sampling scheme that was used to select a subset of training data that was used to train diffdock-pp as reported in our pre-print:
https://github.com/pinder-org/pinder/blob/9c70a92119b844d0d20e35f483b4f1f26b2899c4/src/pinder-data/pinder/data/plot/performance.py#L148-L203

```python
>>> from pinder.data.plot.performance import get_subsampled_train
>>> subsampled = get_subsampled_train(index)
>>> subsampled.shape
(53628, 34)
```  

Nonetheless, I performed some experiments over sweep of differing `batch_size`, `num_workers` and filters vs. no filters.  I did this with the same set of transforms and filters as in the notebook, but increased `num_samples` to 300. 

<img width="2247" alt="image" src="https://github.com/user-attachments/assets/5c3c47fb-971b-4544-9978-323bfede9b36">

In the best case scenario above, you see an average load time of 0.25 seconds per item. In the worst-case scenario with all filters, 0.63 seconds. Extrapolating this linearly to the full train dataset, that would amount to 108.7 hrs in the lower-bound and 273.8 hrs in the upper-bound. If extrapolated to the sub-sampled train, this would be 3.73 hrs and 9.4 hrs of total linear loading time, respectively. Worth noting that this is on a Mac w/plenty of concurrent processes running in the background, so would expect even better performance in other environments. 

Of course, in a typical training cycle, we wouldn't be incurring all of this time as blocking operations. With `num_workers > 0` (and `prefetch_factor`), you can load and process data while the GPU is still busy, thereby "hiding" that time by virtue of concurrent operations.  

Alternatively, you could implement a pre-cached dataset that stores dataset items on disk as e.g. `.pt` files like in the torch-geometric dataloader, if that better suits your infra setup:
https://github.com/pinder-org/pinder/blob/9c70a92119b844d0d20e35f483b4f1f26b2899c4/src/pinder-core/pinder/core/loader/dataset.py#L599-L622


If you have any suggestions for further shaving the 0.25-0.63 second structure I/O, structure-based filtering and transforms, and tensor collation operations, I would love to implement! Note also that this is using `random_mixed` monomers, it would be even faster if we only use holo. (Predicted structures tend to be very large, and in general system size variability is also another potential source of variability). 


Hope this was helpful and let me know if you have any other questions or suggestions!

**Comment by eswan01** [comment]
Hi Daniel,

Thank you for your thoughtful and detailed response! This clears up a lot of my worries/confusion with dataloading. I hadn't understood the value of prefiltering and subsampling in reducing the effective dataset size when I wrote this—reading the PINDER supplement with Diffdock-PP retraining details also helped to clarify the intended filtering/sampling process.

If I manage to significantly speed up dataloading within the current framework, I'll let you know :)
