### ISSUE TITLE
Inclusion of D-peptides in dataset

### ISSUE THREAD

**Issue by alex-hh** [pinder-org/pinder#26]
Hi,

I (and my code) were a bit surprised by entry 3mgn__C1_UNDEFINED--3mgn__L1_UNDEFINED where the ligand seems to be a D-peptide - is it intended that this kind of protein be included in the dataset?

Thanks!

**Comment by danielkovtun** [comment]
Hi, 

Yes, it is expected! It would be unexpected to find this in the `test` split, but the general philosophy behind pinder was to consider _all_ types of PPI for training data and leave it to the user / task to select relevant data mixes / apply filters if certain kinds of structures are not needed. 

Peptides were handled separately, as the foldseek alignments are not reliable for clustering. Peptide chains were all given the cluster label `p` to signify this, but may be paired with a non-peptide protein as is the case for `3mgn__C1_UNDEFINED--3mgn__L1_UNDEFINED`.


There is metadata available in the index and metadata parquets that can help identify this type of system a priori:

Index:
|                   |                                   |
|:------------------|:---------------------------------------|
| split             | train                                  |
| id                | 3mgn__C1_UNDEFINED--3mgn__L1_UNDEFINED |
| pdb_id            | 3mgn                                   |
| cluster_id        | cluster_24953_p                        |
| cluster_id_R      | cluster_p                              |
| cluster_id_L      | cluster_24953                          |
| pinder_s          | False                                  |
| pinder_xl         | False                                  |
| pinder_af2        | False                                  |
| uniprot_R         | UNDEFINED                              |
| uniprot_L         | UNDEFINED                              |
| holo_R_pdb        | 3mgn__C1_UNDEFINED-R.pdb               |
| holo_L_pdb        | 3mgn__L1_UNDEFINED-L.pdb               |
| predicted_R_pdb   |                                        |
| predicted_L_pdb   |                                        |
| apo_R_pdb         |                                        |
| apo_L_pdb         |                                        |
| apo_R_pdbs        |                                        |
| apo_L_pdbs        |                                        |
| holo_R            | True                                   |
| holo_L            | True                                   |
| predicted_R       | False                                  |
| predicted_L       | False                                  |
| apo_R             | False                                  |
| apo_L             | False                                  |
| apo_R_quality     |                                        |
| apo_L_quality     |                                        |
| chain1_neff       | 9.34375                                |
| chain2_neff       | 0.277099609375                         |
| chain_R           | C1                                     |
| chain_L           | L1                                     |
| contains_antibody | False                                  |
| contains_antigen  | False                                  |
| contains_enzyme   | False                                  |


Metadata:
|                               |                                   |
|:------------------------------|:---------------------------------------|
| id                            | 3mgn__C1_UNDEFINED--3mgn__L1_UNDEFINED |
| entry_id                      | 3mgn                                   |
| method                        | X-RAY DIFFRACTION                      |
| date                          | 2010-04-07                             |
| release_date                  | 2011-03-02                             |
| resolution                    | 1.400390625                            |
| label                         |                                        |
| probability                   | 0.0                                    |
| chain1_id                     | R                                      |
| chain2_id                     | L                                      |
| assembly                      | 1                                      |
| assembly_details              | author_and_software_defined_assembly   |
| oligomeric_details            | hexameric                              |
| oligomeric_count              | 6                                      |
| biol_details                  | ?                                      |
| complex_type                  | homomer                                |
| chain_1                       | C1                                     |
| asym_id_1                     | C                                      |
| chain_2                       | L1                                     |
| asym_id_2                     | L                                      |
| length1                       | 45                                     |
| length2                       | 13                                     |
| length_resolved_1             | 45                                     |
| length_resolved_2             | 13                                     |
| number_of_components_1        | 1                                      |
| number_of_components_2        | 1                                      |
| link_density                  | 0.0                                    |
| planarity                     | 3.251953125                            |
| max_var_1                     | 0.955078125                            |
| max_var_2                     | 0.51416015625                          |
| num_atom_types                | 4                                      |
| n_residue_pairs               | 44                                     |
| n_residues                    | 24                                     |
| buried_sasa                   | 639.0                                  |
| intermolecular_contacts       | 0                                      |
| charged_charged_contacts      | 0                                      |
| charged_polar_contacts        | 0                                      |
| charged_apolar_contacts       | 0                                      |
| polar_polar_contacts          | 0                                      |
| apolar_polar_contacts         | 0                                      |
| apolar_apolar_contacts        | 0                                      |
| interface_atom_gaps_4A        | 0                                      |
| missing_interface_residues_4A | 0                                      |
| interface_atom_gaps_8A        | 0                                      |
| missing_interface_residues_8A | 0                                      |
| entity_id_R                   | 1                                      |
| entity_id_L                   | 2                                      |
| pdb_strand_id_R               | C                                      |
| pdb_strand_id_L               | L                                      |
| ECOD_names_R                  | F_UNCLASSIFIED                         |
| ECOD_names_L                  |                                        |


Let me know if this helps clarify!

**Comment by alex-hh** [comment]
Ok cool - makes sense!

I guess I was just not expecting cases where either ligand or receptor was composed entirely of non standard amino acids / HETATM records

There seem to be ~100s of such cases?

Is there a way to filter those using the metadata files?

**Comment by danielkovtun** [comment]
There are a number of different ways to filter, depending on what your use-case is. I'll illustrate a few examples below:

## Filtering out complexes that contain a peptide cluster
```python
from pinder.core import get_index

index = get_index()
index = index.query('~cluster_id.str.contains("p")').reset_index(drop=True)
```

## Filtering out complexes where either chain has fewer than n residues
```python
from pinder.core import get_metadata

meta = get_metadata()
min_length = 30
meta = meta.query(f'(length_resolved_1 >= {min_length}) and (length_resolved_2 >= {min_length})') 
```


## Filtering out complexes where either chain is composed entirely of non-canonical residues
```python
from pinder.core import PinderSystem
from pinder.core.utils import constants as pc

def all_noncanonical(ps: PinderSystem) -> bool:
    canonical = set(pc.AA3LetterCode)
    L_resn = ps.native_L.residue_names
    R_resn = ps.native_R.residue_names
    return any([
        len(set(chain_resn).intersection(canonical)) == 0 
        for chain_resn in [L_resn, R_resn]
    ])


>>> ps = PinderSystem("3mgn__C1_UNDEFINED--3mgn__L1_UNDEFINED")
>>> all_noncanonical(ps)
True
```

Let me know if that helps!

**Comment by alex-hh** [comment]
very helpful, thanks!
