### ISSUE TITLE
Obtaining complete dimer files

### ISSUE THREAD

**Issue by anton-bushuiev** [pinder-org/pinder#30]
Hi 👋!

Is there please a way to obtain complete dimer files (i.e., with both interacting partners in their interacting pose as opposed to two separate files with individual partners)?

For example PINDER id `1a8l__A1_Q51760--1a8l__A2_Q51760.pdb` corresponds to two files `test_set_pdbs/1a8l__A1_Q51760-R` and `test_set_pdbs/1a8l__A2_Q51760-L` containing individual partners. If I simply concatenate the rows of the two files I obtain the following structure:

![image](https://github.com/user-attachments/assets/eea0797b-5e3f-4e5f-b4fa-eb35b9870c76)

Nevertheless, I expected to obtain the interactions as it is in the PDB entry. Can you please consult me how to obtain this structure from the PINDER data?

![image](https://github.com/user-attachments/assets/256aecce-7963-4662-96b5-2cd6e9595ee8)

**Comment by danielkovtun** [comment]
Hi @anton-bushuiev, 

`split="test"` systems have been pre-scrambled to avoid pre-orientation biases and is discussed in this FAQ: 

https://github.com/pinder-org/pinder/blob/20487ac403516f453d8be1b0bdc07a9f7a77d9df/faq.md#what-do-holo-apo-native-and-predicted-structures-within-pindersystem-mean

This was done via this method: 
https://github.com/pinder-org/pinder/blob/20487ac403516f453d8be1b0bdc07a9f7a77d9df/src/pinder-data/pinder/data/get_test_set.py#L18-L52

The ground-truth, two-chain dimer complex is available for all systems and is located in `get_pinder_location() / "pdbs" / f"{id}.pdb"` and is also accessible from the `PinderSystem.native` structure property:
https://github.com/pinder-org/pinder/blob/20487ac403516f453d8be1b0bdc07a9f7a77d9df/src/pinder-core/pinder/core/index/system.py#L144-L146
https://github.com/pinder-org/pinder/blob/20487ac403516f453d8be1b0bdc07a9f7a77d9df/src/pinder-core/pinder/core/index/utils.py#L737

**Comment by anton-bushuiev** [comment]
Hi Daniel! Thank you very much!
