### ISSUE TITLE
Binding site information

### ISSUE THREAD

**Issue by navvye** [pinder-org/pinder#33]
I was wondering if there was a way to get binding site information from the Pinder `Structure`, or if I'd have to download the PDB files and perform some analysis on them to obtain the binding site.

Thanks!

**Comment by danielkovtun** [comment]
Hi @navvye, 

Could you clarify what you mean by binding site? 


The `Structure` object is an interface to the PDB files, and so using it would require having the PDB files on disk. The `PinderSystem` object will automatically download any missing PDB files if you create one for a given pinder ID but the files are not found. There exist several methods on the `Structure` object to get interface residues with options for how to calculate them:
https://github.com/pinder-org/pinder/blob/20487ac403516f453d8be1b0bdc07a9f7a77d9df/src/pinder-core/pinder/core/loader/structure.py#L211-L294 


If by binding site you mean which residues are participating in the interface, then we do have a pre-computed index of these values available via `SupplementaryData` -- 

## `supplementary_metadata` contains residue-level information
Note: these interface residues were defined at a very permissive contact radius / atom definition, specifically to ensure all relevant portions were captured when performing the clustering using Foldseek aligned residues intersecting with interface residues. The residue numbers are collapsed into a comma-separated list per row containing a pinder ID:

```python
>>> from pinder.core import get_supplementary_data
>>> supp_meta = get_supplementary_data("supplementary_metadata")
>>> print(supp_meta.sample(1).T.to_markdown())
```

|                     | 2118332                            |
|:--------------------|:-----------------------------------|
| id                  | 7c9w__C30_A8BJF8--7c9w__E43_P08174 |
| ECOD_ids_R          | e7c9wC1                            |
| ECOD_ids_L          | e7c9wE1,e7c9wE3,e7c9wE2            |
| ECOD_intersection_R | 2                                  |
| ECOD_intersection_L | 0,0,0                              |
| chain_1_residues    | 76,77                              |
| chain_2_residues    | 169,170,171,172                    |
>>> 

Here, `chain_1` means the receptor chain (R) and `chain_2` means the ligand chain (L). 

## `interface_annotations` contains summary information about the interface

```python
>>> from pinder.core import get_supplementary_data
>>> interface_annotations = get_supplementary_data("interface_annotations")
>>> print(interface_annotations.head(1).T.to_markdown())
```

|                               | 0                                    |
|:------------------------------|:-------------------------------------|
| path                          | 6rwh__A1_P31947--6rwh__A2_P31947.pdb |
| intermolecular_contacts       | 61.0                                 |
| charged_charged_contacts      | 11.0                                 |
| charged_polar_contacts        | 6.0                                  |
| charged_apolar_contacts       | 18.0                                 |
| polar_polar_contacts          | 0.0                                  |
| apolar_polar_contacts         | 6.0                                  |
| apolar_apolar_contacts        | 20.0                                 |
| link_density                  | 0.1099853515625                      |
| label                         | BIO                                  |
| probability                   | 0.8359375                            |
| number_of_components_1        | 1                                    |
| number_of_components_2        | 1                                    |
| planarity                     | 4.7890625                            |
| max_var_1                     | 0.452880859375                       |
| max_var_2                     | 0.452880859375                       |
| length1                       | 227.0                                |
| length2                       | 227.0                                |
| num_atom_types                | 4.0                                  |
| chain_id1                     | A1                                   |
| chain_id2                     | A2                                   |
| chain1_id                     | R                                    |
| chain2_id                     | L                                    |
| interface_atom_gaps_4A        | 4.0                                  |
| missing_interface_residues_4A | 0.0                                  |
| interface_atom_gaps_8A        | 64.0                                 |
| missing_interface_residues_8A | 0.0                                  |
| entry_id                      | 6rwh                                 |

**Comment by navvye** [comment]
Hey @danielkovtun,

Thank you so much for the detailed response. My aim was to find the residues intersecting with interface residues.

I actually ended up writing some code for getting interface residues within 5Å, sharing it below in case it helps anyone.

```

from Bio.PDB import *
import numpy as np
from typing import Dict, Set, List, Tuple
from pinder.core import PinderSystem, get_index
import os

class BindingSiteExtractor:
    def __init__(self, pinder_system: PinderSystem, distance_cutoff: float = 5.0):
        """
        Initialize the binding site extractor using a PINDER system.
        
        Args:
            pinder_system: PinderSystem object
            distance_cutoff: Distance cutoff in Angstroms for defining interface
        """
        self.pdb_path = pinder_system.native.filepath
        if not os.path.exists(self.pdb_path):
            raise FileNotFoundError(f"PDB file not found at {self.pdb_path}")
            
        self.parser = PDBParser(QUIET=True)
        self.structure = self.parser.get_structure('protein', self.pdb_path)
        self.distance_cutoff = distance_cutoff
        
        # In PINDER's PDB files, receptor is chain 'R' and ligand is chain 'L'
        self.receptor_chain = 'R'
        self.ligand_chain = 'L'

    def get_binding_site(self) -> Dict[str, Set[Tuple[int, str]]]:
        """
        Get binding site residues between receptor and ligand chains.
        
        Returns:
            Dictionary with binding residues for each chain
            {chain_id: set((residue_number, residue_name))}
        """
        binding_residues = {
            self.receptor_chain: set(),
            self.ligand_chain: set()
        }
        
        # Get the chains
        receptor_chain = None
        ligand_chain = None
        
        for chain in self.structure[0]:  # First model
            if chain.id == self.receptor_chain:
                receptor_chain = chain
            elif chain.id == self.ligand_chain:
                ligand_chain = chain
        
        if not (receptor_chain and ligand_chain):
            # Print available chains to help debug
            available_chains = [chain.id for chain in self.structure[0]]
            raise ValueError(f"Chains R and/or L not found. Available chains: {available_chains}")
        
        # Find interface residues
        for res1 in receptor_chain:
            for res2 in ligand_chain:
                # Skip non-standard residues and hetero-residues
                if res1.id[0] != " " or res2.id[0] != " ":
                    continue
                    
                # Calculate minimum distance between residues
                min_distance = float('inf')
                for atom1 in res1:
                    for atom2 in res2:
                        distance = np.linalg.norm(atom1.get_coord() - atom2.get_coord())
                        min_distance = min(min_distance, distance)
                
                # If residues are close enough, add them to binding sites
                if min_distance <= self.distance_cutoff:
                    binding_residues[self.receptor_chain].add((res1.id[1], res1.resname))
                    binding_residues[self.ligand_chain].add((res2.id[1], res2.resname))
        
        return binding_residues

    def print_binding_site_info(self, binding_residues: Dict[str, Set[Tuple[int, str]]]):
        """Print formatted binding site information."""
        print("\nBinding Site Information:")
        for chain_id, residues in binding_residues.items():
            role = "Receptor" if chain_id == self.receptor_chain else "Ligand"
            print(f"\n{role} Chain {chain_id} ({len(residues)} residues):")
            sorted_residues = sorted(list(residues), key=lambda x: x[0])
            for res_num, res_name in sorted_residues:
                print(f"  {res_name}-{res_num}")

def main():
    # Get test set with apo structures
    index = get_index()
    hetero_test_apo = index.query('(uniprot_L != uniprot_R) and split == "test" and (apo_R and apo_L)')
    hetero_test_apo.reset_index(drop=True, inplace=True)
    
    # Get a specific system
    pinder_id = "1ldt__A1_P00761--1ldt__B1_P80424"
    ps = PinderSystem(pinder_id)
    ps = PinderSystem(pinder_id, apo_ligand_pdb_code="2kmr", apo_receptor_pdb_code="1fmg")
    print(f"Analyzing system: {ps.entry.id}")
    print(f"PDB file path: {ps.native.filepath}")
    print(f"Original Receptor chain: {ps.entry.chain_R}")
    print(f"Original Ligand chain: {ps.entry.chain_L}")
    print("Note: In PINDER PDB files, chains are renamed to 'R' and 'L'")
    
    # Extract binding sites
    extractor = BindingSiteExtractor(ps)
    binding_sites = extractor.get_binding_site()
    extractor.print_binding_site_info(binding_sites)
    
    # Print summary statistics
    print("\nSummary:")
    print(f"Receptor interface residues: {len(binding_sites['R'])}")
    print(f"Ligand interface residues: {len(binding_sites['L'])}")

if __name__ == "__main__":
    main()

```
