### ISSUE TITLE
Predicting Interactions

### ISSUE THREAD

**Issue by cerabinowitz** [pinder-org/pinder#7]
Hi, I’m interested in whether PINDER can predict interactions between two sequences or structures. Is there a method or feature within PINDER for this? Any guidance or insights would be appreciated. Thanks!

**Comment by danielkovtun** [comment]
Hi -- no, PINDER does not provide any models for co-folding or docking inference. It provides a dataset and framework for training and evaluating new methods with a particular attention to data splits to minimize information leakage and maximize generalizability. 

We have provided initial templates as inspiration for how we ran the physics-based methods evaluated in the benchmark included in our publication. Feel free to check out the [`pinder.methods`](https://github.com/pinder-org/pinder/tree/main/src/pinder-methods/pinder/methods) package if that is of interest.
